### ISSUE TITLE
/docker-entrypoint.sh: ignoring /docker-entrypoint-initnuxeo.d/nuxeo.conf

### ISSUE THREAD

**Issue by JonasAymoz** [nuxeo/docker-nuxeo#39]
I have the folowwing error when i start my container :
`/docker-entrypoint.sh: ignoring /docker-entrypoint-initnuxeo.d/nuxeo.conf`

I verified if the file was there and it is.

I'm running the Folowing dockerFile from the docs 
```
FROM nuxeo:10.10
COPY ./nuxeo.conf /docker-entrypoint-initnuxeo.d/nuxeo.conf
```

What i'm i supposed to do to make docker-entrypoint.sh running ?

**Comment by ataillefer** [comment]
Hi,

The message you're getting is not an error, it's simply a log to inform that `/docker-entrypoint-initnuxeo.d/nuxeo.conf` isn't handled as the other files that could be existing in `/docker-entrypoint-initnuxeo.d/` (.zip, .sh or .clid), see https://github.com/nuxeo/docker-nuxeo/blob/master/10.10/docker-entrypoint.sh#L52.
It's as a special case since `nuxeo.conf` is already handled above, see https://github.com/nuxeo/docker-nuxeo/blob/master/10.10/docker-entrypoint.sh#L39.

This shouldn't prevent the container from starting. If that's the case then there's another issue.

Closing the PR, feel free to open a new one if you're facing issues starting the Docker image.
